version: '3'

name: 'sdl_docker'
services:
  html:
    container_name: 'html'
    image: nginx:1.11-alpine
    build: .
    ports:
      - 80:80
    depends_on:
      - dbase

  dbase:
    container_name: 'dbase'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - dbase-data:/var/lib/postgresql/data

volumes:
  html-data:
  dbase-data:

networks:
  mynetwork: